version: '3.8'

services:
  jenkins:
#    image: jenkins/jenkins:lts
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    networks:
      - jenkins
      - nginx-proxy
#    ports:
#      - "8080:8080"
#      - "50000:50000"
    expose:
      - 8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    environment:
      DOCKER_HOST: tcp://jenkins-docker:2375
#      DOCKER_HOST: unix:///var/run/docker.sock
      VIRTUAL_HOST: itasca.co.in
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: itasca.co.in
      LETSENCRYPT_EMAIL: info@itasca.co.in

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    ports:
      - 2375:2375
#    ports:
#      - "2376:2376"
    command: ["dockerd", "--storage-driver", "overlay2"]


networks:
  default:
    driver: bridge

  nginx-proxy:
    external: true

volumes:
  jenkins-data:
  jenkins-docker-certs: